user/getting-started.md
Made some changes to getting started after trying it myself. Later today I will do an install on a completely fresh machine to see if I missed anything.
=> Update on getting-started.md

proposals/README.md, proposals/bip-000.md, proposals/bip-001.md
An initial draft for Babelfish Improvement Proposals.
=> [BIP-0] Index, template and the first BIP draft

README.md, SUMMARY.md, architecture.md, driver/annotations.md, driver/protocol.md, driver/sdk.md, user/protocol.md, user/server-protocol.md
Same as yesterday PR with feedback incorporated, created this new branch to avoid some rebasing hell on that PR.
=> General improvements and fixes

SUMMARY.md, user/server-grpc-example.md, user/server-protocol.md
This page explains a working example using the gRPC protocol to get the tokens of a Python helloworld.
=> gRPC example page

languages.md
- python-driver version bump
- java driver dockerhub link
=> Minor language related fixes

user/getting-started.md
Should close #47 
Depends on a new release of the server docker image.
=> user: Document --log-level server parameter

user/getting-started.md
Changed how to set BBLFSH_DRIVER_IMAGES and give it to a container to avoid parsing issues.
=> changed how to set BBLFSH_DRIVER_IMAGES environment variable

proposals/bip-002.md
This is not a BIP but something like a "WIP" BIP. It provides options for the alternatives proposed in the previous PR and the new ones given from the feedback, and weights advantages and disadvantages to each. The purpose of this PR is to discuss the WIPBIP in it's current form and for the Benevolent Dictator @mcuadros to choose it's own adventure based on the alternatives provided (or the new ones from this PR discussion).
Once that's done I would do a new PR with the BIP in it's final form ready to be included if approved.
=> New rewritten BIP

proposals/bip-002.md
- Added an extended description of the `Incomplete` role.
- Formatting fix.
=> Added clarification about Incomplete roles alone

uast/specification.md
=> Clarification about the positions

SUMMARY.md, user/language-clients.md
=> Added bblfsh clients page

community.md, driver/sdk.md, languages.md, roadmap.md, uast/specification.md, user/getting-started.md, user/language-clients.md, user/server-grpc-example.md, user/server-protocol.md
Changes to reflect usage of SDKv1, updated roles, updated status of projects, etc.
=> Upgrade documentation

user/language-clients.md
=> Updated status of the Scala client.

Makefile, SUMMARY.md, _tools/roles/main.go, uast/roles.md, uast/specification.md
Signed-off-by: Máximo Cuadros <mcuadros@gmail.com>
=> uast: roles.md and tool for autogenerate it

driver/internal-protocol.md, proposals/bip-001.md, user/getting-started.md
This should fix the Travis build.
=> Fix broken links. Re-add example of adding a driver from the local Docker

README.md
=> docs: Add link to doc.bblf.sh

user/getting-started.md
=> macOS compatible example of the server docker volume command

SUMMARY.md, user/getting-started.md
=> dashboard: Add a menu link and a reference in getting started.

uast/specification.md
=> Added a uast::specification::objectives to clarify UAST's objectives

languages.md
=> languages: Fix escaping of notes

driver/sdk.md
=> Update the integration tests' information which the latest changes.

driver/sdk.md
=> Write the correct error when language detection fails.

user/language-clients.md
=> language-clients: Improve xpath query documentation

user/language-clients.md
=> language-clients: Fix typo

user/getting-started.md
=> Change bblfshd mount point info

languages.md
=> languages: Add Bash and PHP drivers

SUMMARY.md, user/uast-querying.md
Part of fix for bblfsh/libuast/issues/45.
=> Add UAST querying page.

user/language-clients.md, user/uast-querying.md
=> Merge user/uast-querying.md and language-clients#query-language.

languages.md
=> Add Ruby driver to the table

languages.md
=> Add typescript driver to docs languages list

user/advanced-usage.md, user/getting-started.md
Plus some typos fixed in other sections of the "advanced usage" page.
Fixes #127.
=> Change --all for --recommended. Document new --all

languages.md
=> languages: Tick annotations for JavaScript

languages.md
=> Remove the tick mark from bash annotations since they need more work

languages.md
=> bash annotations

languages.md
Note that docker image for golang is missing.
=> include Go driver

languages.md
=> Change status of PHP annotations

_tools/languages/main.go, languages.md
Requires https://github.com/bblfsh/sdk/pull/234
* move drivers discovery to SDK
* allow to print the list in json format
* regenerate languages list
=> use driver discovery to generate the list

user/uast-querying.md
=> Add reference to typed filter functions

driver/annotations.md
=> Updated link to slack community

user/getting-started.md
=> Add note and link about SELinux

user/language-clients.md
=> Add docs about the iterators

architecture.md, community.md
=> Fix links and bblfshd name

_tools/roles/main.go, uast/roles.md
Fixes #152
This can actually give a pretty good insight about driver completeness.
And it looks like there are roles that are not being used at all.
=> Update a roles list generator and re-generate the list

SUMMARY.md, proposals/README.md, proposals/bip-004.md, proposals/bip-005.md
Request for comments on:
These BIPs are sent together because, as we decided on the first design meeting, we will not wait for the first one to be accepted, and will implement both in one logical step.
=> Request for comments for BIP-4 and BIP-5

languages.md
=> Updated language list

README.md, uast/specification.md
Signed-off-by: Marcelo Novaes <mnovaes@gmail.com>
=> Clarify UAST meaning in uast/specification.md

bip-index/bip1-purpose-and-guidelines.md, bip-index/bip2-explicit-annotated-status-and-completeness-information.md, using-babelfish/babelfish-protocol.md, using-babelfish/language-clients.md, writing-a-driver/babelfish-sdk.md
From comments on: bblfsh/sdk/issues/257#issuecomment-398075978
cc @smola 
=> Show the need to check Response.Status

using-babelfish/language-clients.md
cc @smola 
Related to: bblfsh/sdk/issues/257
=> Added examples in Python and Scala

using-babelfish/uast-querying.md
Signed-off-by: Anna Tsolakou <tsolakou.a@gmail.com>
=> Fix typo uast-querying doc

using-babelfish/getting-started.md
Signed-off-by: Anna Tsolakou <tsolakou.a@gmail.com>
=> Fix Typo in Getting Started page

bip-index/bip0-template.md, bip-index/bip1-purpose-and-guidelines.md, bip-index/bip2-explicit-annotated-status-and-completeness-information.md
=> Fix typos in BIPs and adjust line breaks

using-babelfish/getting-started.md
=> Fix typos and adjust some wording in Getting Started

bip-index/bip3-agglutinative-roles-language.md
=> Improve BIP3 rendering

driver/transform-dsl.md, uast/roles.md, using-babelfish/grpc-usage-example.md
=> Fix various typos

join-the-community.md, uast/code-to-ast.md, using-babelfish/language-clients.md
=> Fix various rendering

using-babelfish/getting-started.md
=> Less confusing installation instructions

using-babelfish/getting-started.md
Fixes src-d/devrel/issues/77
Fixes #179 
cc @tsolakoua 
=> Add info to bblfshctl parse

using-babelfish/getting-started.md
=> Uppercase docker

using-babelfish/language-clients.md
=> source codes -> source code

SUMMARY.md, using-babelfish/clients.md, using-babelfish/getting-started.md
=> "Language Clients" -> Clients and add clients before querying UAST section.

SUMMARY.md, using-babelfish/getting-started.md
Part of https://github.com/bblfsh/dashboard/issues/149
=> rename dashboard to web client

README.md, uast/representation_v2.md, uast/semantic-uast.md, uast/uast-specification.md, uast/uast_v2.md, using-babelfish/advanced-usage.md
=> Add Semantic UAST and UASTv2 docs, mention migration options

Makefile, _tools/languages/main.go, languages.json, languages.md
Update languages list and generate a static `languages.json` file for driver discovery.
Related to https://github.com/bblfsh/sdk/issues/264
=> Update languages list and serve a static list of official drivers

README.md
=> Add link to the getting started section in the README

uast/semantic-uast.md
@zurk please check the changes and tell me if the relation is clearer now.
=> Clarify relation about @pos, Positions and Position

SUMMARY.md, uast/semantic-uast.md
=> Complete the information on semantic types and cross-ref links

README.md, SUMMARY.md, alternatives.md
Draft. Addresses #35 to some degree. Still worth adding a comparison table before merging.
Please review carefully - my wording might not be correct. And I haven't tried all the systems described here, so the information might be wrong to some degree.
=> Describe how Babelfish compares to other projects

using-babelfish/uast-querying.md
Fixes #206.
Fixes #207.
cc @zurk 
=> Update the querying page

using-babelfish/getting-started.md
Fixes bblfsh/bblfshd/issues/203.
Thanks @BFergerson, please take a look and tell me if its clearer now.
=> Add info about ostree on the standalone page

alternatives.md
=> Improve the English of the alternatives

languages.json, languages.md
Update languages list to include the latest changes to C++ driver and SDK version dump.
=> Update languages list

using-babelfish/clients.md
=> Update clients documentation

uast/uast-v2.md
Part of the https://github.com/bblfsh/sdk/pull/314
Instructions will be available at https://docs.sourced.tech/babelfish/uast/uast-v2#visualization
=> Add visualization instructions

using-babelfish/advanced-usage.md
To redirect visitors there :dagger:
=> Link clients docs in advanced-usage

MAINTAINERS
=> Make @creachadair maintainer of this project

languages.json, languages.md
=> Updated languages list

languages.json, languages.md
Result of the `make languages`
=> languages: re-generate the list of drivers

using-babelfish/getting-started.md
=> add example for single driver install

using-babelfish/clients.md
Current documentation demonstrates the v1 client. Update the example for the current version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/documentation/262)
=> Update documentation for the Python client

using-babelfish/clients.md
Switch to new import paths, remove the use of deprecated functions and inline some operations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/documentation/263)
=> Update Go client example

uast/representation-v2.md, uast/uast-encoding-v2.md, uast/uast-specification-v2.md, using-babelfish/babelfish-protocol.md
Add a UAST decoding spec written based on the design doc and Go implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/documentation/251)
=> Add a UAST decoding spec

bip-index/bip3-agglutinative-roles-language.md, join-the-community.md, using-babelfish/clients.md
Last artefact of the https://github.com/bblfsh/documentation/issues/231
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/documentation/267)
=> Rename clients in the doc

_tools/languages/main.go, languages.md
Add a (secondary) language aliases table, as discussed in #255.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/documentation/264)
=> Add a language aliases table

join-the-community.md, writing-a-driver/babelfish-sdk.md
Update the "Writing a driver" section. The purpose of the PR is not to make it perfect, but at least to make it closer to the current state.
There are still a lot of TODOs which should be addressed in the following PRs.
With those changes, you should be able to build a basic "echo" driver and know how to run the build system and the tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/documentation/269)
=> Update the "Writing a driver" section

Jenkinsfile, Makefile, _tools/ci-updater/main.go, go.mod, go.sum
Once in a period jenkins job starts and performs `make languages command`
then it tries to create PR with language drivers versions update if needed.
Additionally curl trigger has been added just for the case when weekly cron trigger fails with rate limits or whatsoever
closes #275
Signed-off-by: lwsanty <lwsanty@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/documentation/276)
=> auto-update languages

languages.json, languages.md
=> auto-update-languages_2019-09-13T13-13-43

CODEOWNERS, MAINTAINERS
Part of bblfsh/bblfshd#307.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/documentation/279)
=> Add CODEOWNERS, update MAINTAINERS.

_tools/ci-updater/main.go
Signed-off-by: lwsanty <lwsanty@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/documentation/278)
=> Automated languages update -> change PR title

LICENSE.md, README.md
Signed-off-by: kuba-- <kuba@sourced.tech>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/documentation/282)
=> Add CC license

languages.json, languages.md
regular languages update
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bblfsh/documentation/281)
=> Automated update
